fixed tests and modified actions file to block if any tests fail (#62)
* fixed test

* fixed test

* sample test

* code coverage at 95%

* commented delete request func as it is not used currently

* commented delete request func as it is not used currently

* Update pytest.yml

* coverage config

* minor change

* minor change

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -20,9 +20,10 @@ jobs:
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         run: |
           pip install -r requirements.txt && pip install pytest pytest-coverage
-          python -m pytest test/ --cov=. --junit-xml=test-reports/report.xml --cov-report=term-missing --cov-fail-under=90 | tee pytest-coverage.txt
+          python -m pytest test/ --cov=. --junit-xml=test-reports/report.xml --cov-report=term-missing --cov-fail-under=95 | tee pytest-coverage.txt
           echo "STATUS=$(cat pytest-coverage.txt | grep 'Required test' | awk '{ print $1 }')" >> $GITHUB_ENV
           echo "${{ env.STATUS }}"
+          echo "FAILED=$(cat test-reports/report.xml | awk -F'=' '{print $5}' | awk -F' ' '{gsub(/"/, "", $1); print $1}')" >> $GITHUB_ENV
       - name: Pytest coverage comment
         uses: MishaKav/pytest-coverage-comment@main
         if: ${{ always() && github.ref != 'refs/heads/master' }}
@@ -31,5 +32,5 @@ jobs:
           pytest-coverage-path: ./pytest-coverage.txt
           junitxml-path: ./test-reports/report.xml
       - name: Evaluate Coverage
-        if: env.STATUS == 'FAIL'
+        if: ${{ (env.STATUS == 'FAIL') || (env.FAILED > 0) }}
         run: exit 1
